project: SearchEval
wandb: true  # whether to log to wandb
seed: 0  # random seed

data:
  root: ./data
  name: chatbot_arena_palms_vs_vicuna  # name of dataset
  group2: "vicuna-13b"  # name of group 1
  group1: "palm-2"  # name of group 2
  purity: 1.0  # how much of each concept is in each group (1.0 means perfect seperation, 0.5 means perfect mix)

proposer:  # LLM Proposer
  # method: DualSidedLLMProposer  # how to propose hypotheses
  method: LLMOnlyProposer
  model: gpt-4o  # model used in method
  num_rounds: 50 # number of rounds to propose
  num_samples: 20  # number of samples per group to use
  sampling_method: random  # how to sample
  num_hypotheses: 3  # number of hypotheses to generate per round
  prompt: LLM_DIFF_PROMPT  # prompt to use

ranker:  # LLM Ranker 
  method: LLMOnlyRanker
  model: gpt-4o-mini

evaluator:
  method: NullEvaluator  # how to evaluate hypotheses
